### ISSUE TITLE
mb executable missing

### ISSUE THREAD

**Issue by cdoorenweerd** [naturalis/puppet-mrbayes#1]
Hi Hugo,

The 'mb' command cannot be found when I try to run it, as far as I can tell it did not compile the mb executable. I think this is because in the compile mrbayes section:
>    cwd         => "/opt/mrbayes-${version}/src",

the dir is actually

> "/opt/mrbayes-${version}/mrbayes-${version}/src"

for some reason :)

**Comment by hduijn** [comment]
Somehow the contents of the source file of mrbayes is changed, all content is added to a directory with the name mrbayes_3.2.5. Probably done on 28-03 just after the commit. 

Puppet code has now been changed to work with the new tar file and everything should work fine again.
